### PR TITLE
fix: change etcd volumes data path in container

### LINKED ISSUE #171: docker compoest start image, but etcd start failed
Error is this : 
image

### PR DESCRIPTION
**Pull request by Simolx**
Closes #171 , #173 
Change etcd volumes data path in example module.

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
> > @younglifestyle could the method provide by @anyeshe fix your problem
> 
>failed. Etcd can't see the log. the configuration is here
image

>_Originally posted by @younglifestyle in https://github.com/apache/apisix-docker/issues/171#issuecomment-836329780_

It seems would be better to change the permission of `./etcd_data` or add docs about it, as #171 suggests, since the fix right now could not work as expected

**Comment by tokers** [comment]
> > > @younglifestyle could the method provide by @anyeshe fix your problem
> 
> > 
> 
> >failed. Etcd can't see the log. the configuration is here
> 
> image
> 
> 
> 
> >_Originally posted by @younglifestyle in https://github.com/apache/apisix-docker/issues/171#issuecomment-836329780_
> 
> 
> 
> It seems would be better to change the permission of `./etcd_data` or add docs about it, as #171 suggests, since the fix right now could not work as expected

Agree with that.

**Comment by Yiyiyimu** [comment]
@tokers Several users met with this problem, I think we need to fix it now.

And the orinigal error `etcdmain: cannot access data directory: open /bitnami/etcd/data/.touch: permission denied` might result from `ETCD_DATA_DIR: /etcd_data` not effective, so etcd still take the default path `/bitnami/etcd` as data dir.

If we ignore the reason why it's not effective (I failed to find it), we could take this PR to fix the problem

**Review by Yiyiyimu — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
@Simolx Thanks for your contribution!

**Comment by Yiyiyimu** [comment]
Hi @thomasroshin Yes you're right it is not fixed in the latest image, considering the time this PR got merged is after the time the latest image got released. Maybe you could try to build the image yourself, or use the `dev` image.

**Comment by thomasroshin** [comment]
Thank you. I am able to run it.

**Comment by duandao1950** [comment]
[root@localhost example]# docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

-----------------------------------

etcd_1              | 2021-07-01 11:57:38.007837 I | embed: advertise client URLs = http://0.0.0.0:2379
etcd_1              | 2021-07-01 11:57:38.007935 C | etcdmain: cannot access data directory: mkdir /bitnami/etcd/data: permission denied

---------------------------------------------

 etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    privileged: true
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

-----------------------

please help!

**Comment by carlzhao** [comment]
change etcd version to 3.4.14 solves this problem.

  etcd:
    image: bitnami/etcd:3.4.14
    user: root
    restart: always
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

**Pull request merged**
