### PR TITLE
fix: example containers using old images

### PR DESCRIPTION
**Pull request by lucabotti**
Fixed issue for #417

### CODE REVIEW

**Comment by zll600** [comment]
@monkeyDluffy6017 Could you help review this?

**Comment by monkeyDluffy6017** [comment]
It looks like there is something wrong with the ci

**Comment by lucabotti** [comment]
The issue seems related to unavailability of Docker hub - RH build passed, Debian was not.

**Comment by monkeyDluffy6017** [comment]
Could you fix this error?
image

**Comment by lucabotti** [comment]
Sorry, @monkeyDluffy6017 I guess is outside of my reach.

image

Certificate has expired on 22nd of January. Builds outside of China works correctly.

**Comment by monkeyDluffy6017** [comment]
@lucabotti you can do like this:
image

**Comment by monkeyDluffy6017** [comment]
I think we don't need the latest version but the lts version

**Pull request closed without merging**
