### PR TITLE
feat: do not overwrite existing yaml files

### PR DESCRIPTION
**Pull request by kamly**
fix https://github.com/apache/apisix-docker/issues/482
relevant  https://github.com/apache/apisix-docker/pull/487

### CODE REVIEW

**Review by monkeyDluffy6017 — APPROVED** [review]

**Review by Revolyssup — APPROVED** [review]

**Comment by monkeyDluffy6017** [comment]
@kamly please make the ci pass

**Comment by kamly** [comment]
done, merge master

**Comment by monkeyDluffy6017** [comment]
please make the ci pass

**Review by monkeyDluffy6017 — CHANGES_REQUESTED** [review]
The ci is still failed

**Comment by kamly** [comment]
oh....

**Comment by kamly** [comment]
I run action again, ci success  https://github.com/kamly/apisix-docker/actions/runs/6038652144/job/16385502632?pr=1

**Review by monkeyDluffy6017 — APPROVED** [review]

**Pull request merged**
