### PR TITLE
chore: change the user for all-in-one

### PR DESCRIPTION
**Pull request by Hazel6869**
fix the issue https://github.com/apache/apisix-docker/issues/404

has test in my local
image

### CODE REVIEW

**Comment by soulbird** [comment]
Wouldn't it be better to use `sudo`? can you try

**Comment by soulbird** [comment]
@Hazel6869

**Comment by Hazel6869** [comment]
> Wouldn't it be better to use `sudo`? can you try

ok i try it

**Comment by Hazel6869** [comment]
> 

@soulbird  Hi, I have try it,  but it not ok, There is no sudo in the image

**Comment by soulbird** [comment]
So, will APISIX be executed with root privileges in the end?

**Comment by Hazel6869** [comment]
> So, will APISIX be executed with root privileges in the end?

Yes, it was like this before

**Comment by soulbird** [comment]
You set the APISIX startup user to `apisix` in other PR, but here it is `root`, which seems a bit fragmented. But all_in_one is just for testing, I can accept your adjustment

**Review by soulbird — APPROVED** [review]

**Comment by Hazel6869** [comment]
> You set the APISIX startup user to `apisix` in other PR, but here it is `root`, which seems a bit fragmented. But all_in_one is just for testing, I can accept your adjustment

thx ❤️

**Review by spacewander — APPROVED** [review]

**Pull request merged**
