### PR TITLE
feat: add apisix-dashbaord 

### PR DESCRIPTION
**Pull request by anjia0532**
feat: add apisix-dashbaord

### CODE REVIEW

**Comment by membphis** [comment]
@nic-chen please take a look at this PR

**Comment by nic-chen** [comment]
@anjia0532 

We could mv the [dockerfile](https://github.com/apache/apisix-dashboard/blob/master/Dockerfile) of Dashboard into this repo, and also mv the [CI](https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/deploy-with-docker.yml) for it.

Thanks.

**Comment by anjia0532** [comment]
@nic-chen 将dashboard库的dockerfile挪到apisix-docker里会不会有点粗暴？不过道理也能说得通，毕竟apisix本身也没有dockerfile，相当于apisix的docker相关的都集合到apisix-docker里

我这个PR是因为在看官方文档时想quickstart一个比较全的demo（包含dashboard），但是还得去别的地方找资料，自己改

**Comment by nic-chen** [comment]
> 我这个PR是因为在看官方文档时想quickstart一个比较全的demo（包含dashboard），但是还得去别的地方找资料，自己改

Sorry, I was misled by pr title.
What I said above should be done by another pr.

**Comment by anjia0532** [comment]
@nic-chen  OK

**Comment by nic-chen** [comment]
@anjia0532  CI failed, please have a look

**Comment by anjia0532** [comment]
我改的是md文档，不会触发这个错误。
image

**Comment by nic-chen** [comment]
> @nic-chen 
> 
> 我改的是md文档，不会触发这个错误。
> 
> image
> 
> 
> 
> 

OK, could you help fix it? we could not merge it when CI failed.

**Comment by anjia0532** [comment]
give up this. I'll close this PR.

**Comment by gxthrj** [comment]
Reopen this PR, but all CI passed. @anjia0532

**Review by gxthrj — APPROVED** [review]

**Comment by gxthrj** [comment]
@nic-chen  Please have a look

**Comment by nic-chen** [comment]
how does the CI pass?

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
