### PR TITLE
feat: replace openresty with apisix-base

### PR DESCRIPTION
**Pull request by Xunzhuo**
replace `openresty` with`apisix-base`

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by nic-6443** [comment]
luarocks not found in `api7/apisix-base:1.19.3.2.1`

**Comment by nic-6443** [comment]
> && luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl/lib \
    && luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl/include \

`api7/apisix-base:1.19.3.2.1` don't contain OPENSSL* dir

**Comment by tokers** [comment]
> > && luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl/lib 
> >     && luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl/include \
> 
> `api7/apisix-base:1.19.3.2.1` don't contain OPENSSL* dir

Use dir `/usr/local/openresty/openssl111`. @Xunzhuo

**Comment by Xunzhuo** [comment]
cc @tokers @nic-6443 @spacewander  , please take a look, I think it is OK now. 
And the docker image `api7/apisix-base:1.19.3.2.1` has been updated.

**Review by spacewander — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Pull request merged**
