### PR TITLE
fix apisi-dashboard 3.0.0  dockerfile go version not consist with the project code

### PR DESCRIPTION
**Pull request by StevenBrown008**

### CODE REVIEW

**Comment by StevenBrown008** [comment]
https://github.com/apache/apisix-dashboard/blob/v3.0.0/api/go.mod

**Comment by StevenBrown008** [comment]
dashboad-go

**Comment by StevenBrown008** [comment]
@gxthrj @spacewander @bzp2010 @soulbird @moonming  please cc

**Comment by soulbird** [comment]
I think we should upgrade the version of golang in the dashboard instead of downgrading the version here

**Comment by StevenBrown008** [comment]
> I think we should upgrade the version of golang in the dashboard instead of downgrading the version here

As a docker package project, maybe we just need to be consist with the real project  code

**Pull request closed without merging**
