### PR TITLE
fix missing conf that cause docker startup to fail

### PR DESCRIPTION
**Pull request by to2false**
Related to: https://github.com/apache/apisix-docker/issues/69

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Comment by moonming** [comment]
@gxthrj I remember this file will be sync from apisix repo,right?

**Comment by membphis** [comment]
the CI failed, here is the reason: https://github.com/apache/apisix-docker/issues/80

**Comment by gxthrj** [comment]
I think we can close this PR now , since we use  `config-default.yaml` to solve this kind of problems.

**Comment by to2false** [comment]
Agree with @gxthrj , so closed it.

**Pull request closed without merging**
