### PR TITLE
Fix granafa dashboard iframe policy

### PR DESCRIPTION
**Pull request by donlinglok**
Hi,
I was trying to run the docker example with the below command:
```
git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example
docker-compose -p docker-apisix up -d
```
After I set the Grafana Address `http://localhost:3000/`, it displays error:
```
Refused to frame 'http://localhost:3000/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```
image

This can be fixed by adding config `frame-src *` in `example\dashboard_conf\conf.yaml`:
```
content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-src *"  # You can set frame-src to provide content for your grafana panel.
```

After patch:
image

### CODE REVIEW

**Comment by tao12345666333** [comment]
#340

**Comment by donlinglok** [comment]
> #340
@tao12345666333 
Dear,
I checked that PR, that solution needs a manual change to the config for the beginner. 
```
frame-src xxx.xxx.xxx.xxx:3000 -> frame-src *
```
My change can be run successfully with the same starter code after merging with the master branch.
```
git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example
docker-compose -p docker-apisix up -d
```

and without unnecessary configuration.

**Comment by donlinglok** [comment]
> @donlinglok Sorry for delay.
> 
> Would you please reopen this one?
> 
> Your explanation above makes sense. Let's merge this one

Thanks!

**Comment by tao12345666333** [comment]
@bzp2010  PTAL, thanks

**Comment by soulbird** [comment]
@donlinglok Can you merge master's code and make CI  pass?

**Comment by donlinglok** [comment]
> @donlinglok Can you merge master's code and make CI pass?

merged, thank you!

**Review by tokers — APPROVED** [review]

**Review by soulbird — APPROVED** [review]

**Pull request merged**
