### PR TITLE
fix: sed not suitable for docker if config.yaml is volume mounted #529

### PR DESCRIPTION
**Pull request by jingzhao-self**
### Description

fix: config.yaml couldn't be volume mounted when using standalone Deployment modes (https://github.com/apache/apisix-docker/issues/529)

### CODE REVIEW

**Review by monkeyDluffy6017 — APPROVED** [review]

**Comment by kayx23** [comment]
Should this be applied to 3.7.0 as well and have new images pushed? Or just wait for 3.8.0?

**Comment by monkeyDluffy6017** [comment]
@kayx23 Yeah, it will affect version 3.6.0 and 3.7.0, maybe we should update both 3.6.0 and 3.7.0 images

**Comment by kayx23** [comment]
Following up on this PR. Do we have to wait for the test cases or are we comfortable with this fix to move ahead?

**Comment by monkeyDluffy6017** [comment]
It will affect the release of apisix, so we could approve this release first, i have created an issue here for the test case: https://github.com/apache/apisix-docker/issues/536

**Comment by kayx23** [comment]
Whose review are we waiting on now?

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
