### PR TITLE
ci: release on multiarch for apisix image on alpine

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

So it would be easier to run on Mac M1 😿 

Ref: 
1. https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
2. https://github.com/docker/buildx

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
Close since using the wrong branch

**Comment by Yiyiyimu** [comment]
image
Good to go~

**Comment by Yiyiyimu** [comment]
cc @gxthrj @tao12345666333 @starsz PTAL

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Review by starsz — APPROVED** [review]
Can we support build apisix-dashboard on multi-arch?

**Comment by Yiyiyimu** [comment]
> Can we support build apisix-dashboard on multi-arch?

> can not build dashboard multiarch image since yarn build failed. ref: https://github.com/Yiyiyimu/apisix-docker/runs/3053802787?check_suite_focus=true

@starsz sorry I'm not familiar with front end

Hi @guoqqqi do you have any progress on this problem

**Comment by tao12345666333** [comment]
> Can we support build apisix-dashboard on multi-arch?

It can be added in other PR. Let's merge this PR.

**Comment by guoqqqi** [comment]
image
On M1, `make build-dashboard` I encountered this error
@Yiyiyimu

**Comment by Yiyiyimu** [comment]
We'll fix the dashboard image later in another PR

**Comment by Yiyiyimu** [comment]
I could run dashboard docker build on m1 so there's nothing to do with the building process itself.

Since it stuck at `yarn build`, a large chance is we lack of memory since we also deploy `QEMU` to simulate arm environment, as [ref](https://stackoverflow.com/questions/59868448/rpc-error-code-unknown-desc-failed-to-build-llb) suggested. So one possible way I think is to use travis CI to build the image, since travis supports arm machine by itself so we could remove the rely on QEMU.

**Pull request merged**
