### PR TITLE
feat: Quickly build a local development and debugging environment

### PR DESCRIPTION
**Pull request by cj2a7t**
A fast way to establish a local development environment for APISIX is provided in the APISIX Docker repository based on debian-dev. The following guide demonstrates setting up an APISIX development environment using VS Code.

### CODE REVIEW

**Comment by cj2a7t** [comment]
Hi team, who do I need to help with the review?

**Comment by lingsamuel** [comment]
This repo is not for how-to-use documentation. Please file PR in the main repo

**Comment by monkeyDluffy6017** [comment]
Thanks for your contribution! @kayx23 could you help to review this pr?

**Comment by kayx23** [comment]
Please update the markdown docs to pass the markdownlint CI check. Thanks.

**Review by shreemaan-abhishek — CHANGES_REQUESTED** [review]
please add a github action workflow that tests this setup.

**Review by kayx23 — CHANGES_REQUESTED** [review]
Please update the markdown docs and pass the markdownlint CI check. Thanks.

**Pull request closed without merging**
