### PR TITLE
chore: divide dockerfile `RUN` command

### PR DESCRIPTION
**Pull request by shreemaan-abhishek**
This will increase the layers in the docker container thereby improving the docker image scan for vulnerabilities.

### CODE REVIEW

**Comment by soulbird** [comment]
Why do we need this? Did you successfully build this image locally?

**Comment by shreemaan-abhishek** [comment]
Yes it works.

**Comment by monkeyDluffy6017** [comment]
Could you show us that why do you increase the layers by adding two more `run` command?

**Comment by lingsamuel** [comment]
It will definitely cause apt cache to remain in the generated image.

**Comment by shreemaan-abhishek** [comment]
> Could you show us that why do you increase the layers by adding two more run command?

Docker scout scans images based on layers, more layers = better segregation of source of CVEs.

**Comment by monkeyDluffy6017** [comment]
I don't think it's necessary to do this only for CVEs.

**Pull request closed without merging**
