### PR TITLE
feat: add dashboard support for docker-compose-arm64.yml

### PR DESCRIPTION
**Pull request by leslie-tsang**
fix https://github.com/apache/apisix/issues/6086

### CODE REVIEW

**Review by zaunist — APPROVED** [review]
/LGTM

**Review by spacewander — APPROVED** [review]

**Comment by zaunist** [comment]
@leslie-tsang Is apisix-base compatible for apisix(arm64) now?

**Comment by zaunist** [comment]
> > @leslie-tsang Is apisix-base compatible for apisix(arm64) now?
> 
> Not yet, Let's merge it after `apisix-base` is ready for `arm64`.

Got it.

**Review by bzp2010 — APPROVED** [review]

**Comment by bzp2010** [comment]
### Update
The latest versions of arm64 are currently supported, they include 2.10.3, 2.10.4, 2.12+.

**Pull request merged**
